export const navLinks = [
  { to: "/", label: "Home" },
  { to: "/letter", label: "Letter" },
  { to: "/cake", label: "Make a Wish" },
  { to: "/code", label: "Birthday Code" },
  { to: "/crossword", label: "Puzzle" },
  { to: "/fifty", label: "20 Reasons" },
  { to: "/hero", label: "Big Sister" },
  { to: "/gallery", label: "Gallery" },
  { to: "/his-words", label: "A Note" },
  { to: "/my-reply", label: "Memory Reel" },
  { to: "/prayers", label: "Blessings" },
  { to: "/promises", label: "Promises" },
  { to: "/wishes", label: "Wishes" },
  { to: "/finale", label: "Closing Letter" },
] as const;
